### ISSUE TITLE
Pregunta : Theme Child

### ISSUE THREAD

**Issue by loorlab** [JuanJavier1979/Zircone-Theme#1]
Saludos Juan, Este Theme Zircone lo usas como Theme Child ? Y tienes al Parent Theme como Underscores ? O usas el Theme Zircone como un Theme Parent y adaptas la funcionalidad ?

Mil gracias

**Comment by JuanJavier1979** [comment]
Hola LOOR Lab.
Este tema, Zircone, aunque basado en Underscores no es un Child de Underscores.
Zircone es un Parent Theme y se pueden crear Childs fácilmente. Voy a subir un ejemplo.

Saludos.

**Comment by loorlab** [comment]
Mil gracias, te encontramos por esta conferencia https://www.youtube.com/watch?v=52E-Fq07UnY y al final de la misma alguien te hace la pregunta que hicimos, entonces para aclarar : 

1) Cuando creaste Zircone lo pensaste siempre para usar como un Theme Parent.
2) Si lo usamos le debemos crear un Theme Child a partir de Zircone.

Hemos estado indagando y parece que esa sentencia del código fuente alcanza a confundir.

En verdad gracias por tu oportuna respuesta.

Muy buena la conferencia de _s .

**Comment by JuanJavier1979** [comment]
Gracias por tus comentarios.

1) Sí
2) Sí, ya he subido un ejemplo de Child: https://github.com/JuanJavier1979/Zircone-Child-Theme

Para aclarar: Zircone está basado en el Starter Theme Underscores, y cualquier Tema basado en Underscores se debería de usar como Parent. Nunca crear un Child de Underscores.

¿Qué parte del código es confusa?

**Comment by loorlab** [comment]
Nos referimos a esta sentencia en underscores : "Hi. I'm a starter theme called _s, or underscores, if you like. _I'm a theme meant for hacking so don't use me as a Parent Theme_. Instead try turning me into the next, most awesome, WordPress theme out there. That's what I'm here for." 

Mil gracias por las aclaraciones y por el Theme Child.

Muy buen theme.
